project:
  type: website
  output-dir: docs

website:
  title: "Machine learning basics"
  description: "Show basic machine learning code and quick overview."
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: main
  repo-url: https://github.com/AhmedAredah/MachineLearningBasics

  navbar:
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AhmedAredah
      - icon: twitter
        href: https://twitter.com/AhmedAredah

  sidebar:
    style: "docked"
    alignment: "left"
    search: true
    contents: auto
    width: 500px

  page-footer: 
    left: "Copyright 2023, Ahmed Aredah" 
    right: 
      - icon: github
        href: https://github.com/AhmedAredah
      - icon: twitter 
        href: https://twitter.com/AhmedAredah 

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    toc-expand: 2
    max-width: 500px
    html-math-method: katex
    code-fold: false
    code-summary: "Show the code"