---
title: "1.1-Describe Data"
author: "Ahmed Aredah"
date: "11.4.2023"
format: html
editor: visual
categories:
    Basic Probability theories
---

In the process of understanding and leveraging data for machine learning and analytical purposes, describing and summarizing the data is a pivotal step. Each type of measurement scale---nominal, ordinal, interval, and ratio---has specific statistical methods that can be used to provide a clear and concise summary of the data. These methods are crucial in extracting meaningful patterns and insights which can guide further analysis and model building.

## Nominal Scale

With data on a nominal scale, which involves categorization without an intrinsic order, we can:

-   Count the number of **cases per category** to understand frequency distribution.

-   Determine the **mode**, which is the most frequently occurring category in the dataset.

-   Use a **contingency table** to display the frequency distribution among multiple categories and understand the correlation between different nominal variables, especially within multivariate data sets.

## Ordinal Scale

Ordinal scale data is categorical data with a clear order or rank. For ordinal data, we utilize all the descriptive methods of *nominal* data, plus:

-   The **median**, which is the middle value when all observations are ordered from the least to the greatest.

-   **Percentiles**, which divide the data into 100 equal parts, helping in understanding the distribution across the scale.

## Interval and Ratio Scale

For data on interval and ratio scales---which have ordered categories and meaningful differences between values---the following statistical descriptors are used:

-   The **mean** offers a measure of central tendency, providing an average value.

-   The **standard deviation** measures the amount of variation or dispersion in a set of values.

-   **Correlation** coefficients can illustrate the strength and direction of the relationship between multiple variables in multivariate data.

-   The **relative standard deviation** or **coefficient of variation** is specific to the ratio scale and is used to standardize the standard deviation relative to the mean, offering a dimensionless measure of variability.

Understanding these statistical descriptors and their appropriate application is essential for anyone venturing into data analysis. By accurately describing data, analysts and machine learning practitioners can make well-informed decisions about the types of analysis that are most appropriate for their data and can begin to discern the stories that the data are telling.
